### ISSUE TITLE
add-in registered but not loading 2019SP4

### ISSUE THREAD

**Issue by nemecben** [jsculley/AutoGetReferencedAddin#1]
The .msi appears to register the add-in and it shows in the SW Add-in manager tool.  However, the add-in will not load.  I thought is was conflict with another SW add-in I had written so removed that restarted PC then ran the msi again.  Same behavior.  Tried other workstations, same behavior.

Code shows use of IEdmVault21 but 2019 just has IEdmVault20, possible version issue.

Also curious that when in the SW Add-in manager tool, the tooltip when hovering over this add-in shows the path to other add-in.  Was my add-in first, after removing that add-in it now shows path to the composer plugin dll.

![image](https://user-images.githubusercontent.com/25161718/175119319-dbe7fad1-0107-4997-b582-844d591d868a.png)

Other workstation shows SolidProfessor add-in path:
![image](https://user-images.githubusercontent.com/25161718/175119424-86f41438-f205-40a7-83eb-b8da171239b8.png)

I tried compiling from source but I'm getting error about MSBuildCommunityTasks which I am researching next.

C:\source\repos\AutoGetReferencedAddin-0.1\AutoGetReferencedAddin-0.1\AutoGetReferencedAddin\AutoGetReferencedAddin.csproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\MSBuildCommunityTasks\MSBuild.Community.Tasks.Targets" was not found. Also, tried to find "MSBuildCommunityTasks\MSBuild.Community.Tasks.Targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\bnemec\AppData\Local\Microsoft\VisualStudio\15.0_75df93da\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\source\repos\AutoGetReferencedAddin-0.1\AutoGetReferencedAddin-0.1\AutoGetReferencedAddin\AutoGetReferencedAddin.csproj

**Comment by jsculley** [comment]
Something is broken in the MSI file.  I made a few last minute tweaks and didn't test it (Bad Developer!!).  I just downloaded it and I am seeing the same behavior.  I will get it corrected.

For building from source, you just need to install the [MSBuild Community Tasks](https://github.com/loresoft/msbuildtasks)

In fact, if you are building from source, you don't even need the Community Tasks.  i am only using it to have a build task that ZIPs up the project source code to include it in the MSI file.  In Visual Studio, you can right click the add-in project and Unload it.  Then right click the project and select **Edit Project File**.  Comment out line 4:

 

and comment out lines 158-165:



This will disable the ZIP task.  Reload the project and you can then build just the add-in project and debug it directly without having to deal with the Installer project or install it from an MSI.

**Comment by jsculley** [comment]
I've replaced the MSI file with a Debug build version.  There is some setting that isn't correct between the Release and Debug build configs that is breaking the MSI file.  I will have to track it down.

**Comment by nemecben** [comment]
MS Build Tasks:  I had tried installing the VS Extension through the IDE but that was no help.  From your link I tried installing nuget though the PM but it could not because there was no project loaded and the project would not load without it.  So I installed using the .msi from git.  After that the add-in project loads.  The installer does not load but that's another topic.

Continuing with the sources I previously downloaded I tired to build but the EDM and SW refs were not resolving.  I never knew whether to use edmlib or the EDM.Interop.epdm.  I forget where I found the writeup between the two, probably Xarial, but I've switched all my SW/PDM projects to using the Interops:

`//using EdmLib;
using EPDM.Interop.epdm;

//using SldWorks;
using SolidWorks.Interop.sldworks;
using SolidWorksTools;
//using SWPublished;
using SolidWorks.Interop.swpublished;`

Also, I've learned to never embed interop types when using the SW APIs.  Seems to inevitably cause conflicts when loading modules or registering.

Some of the types have different names mainly the SWapp.  Also dropped IEdmVault21 to 20 and IEdmFile17 to 16 for compatibility with 2019.

Lastly I set the Platform to x64 as there's no need to support 32bit for CAD add-ins anymore, that know of.

It registers the add-in at build time now and next time I started SW on my development VM the add-in loaded automatically and appears to function.  I will register the dlls on my workstation tomorrow morning and test out there.

**Comment by jsculley** [comment]
The references not resolving is due to the fact that your SW/EPDM versions aren't 2022.  I would recommend trying to change the refs to the non-interop 2019 ones.  Don't Browse to them, just select them directly from the COM section of the references dialog.  The less differences between your build and mine, the better.  Selecting x64 for the Platform isn't going to make a difference and may in fact cause problems.  AnyCPU is the default for a reason.  Some libraries require EmbedInteropTypes to be set.  Particularly, for PDM add-ins.  This is an SW add-in so it most likely doesn't matter.  Again, the less you change, the better.

The Installer project requires that you have the [Wix Toolset](https://wixtoolset.org/releases/) installed.  I wouldn't worry about the Installer until you are ready to distribute to  users.  Debugging the add-in project directly from Visual Studio is the best way to work.

**Comment by jsculley** [comment]
I've added #2 as an Enhancement request to backport the codebase to other SW versions.  I'll add branches for SW versions as needed.

**Comment by jsculley** [comment]
The failure of the add-in to load properly was due to a missing 'Register for COM Interop' for the add-in project and an improper preprocessor variable definition in the installer project for the Release build settings.  I've corrected this and replaced the MSI file with a rebuilt Release version.

**Comment by nemecben** [comment]
OK.  I downloaded sources again, put them in new folder.  I assume the new MSI is compiled for 2022?

- The refs to the tlbs were broken when project loaded in VS (I'm guessing due to installed version of SW/PDM being older?)   This time I added refs to the tlbs from COM as instructed and left Interops embedded as they are in your project.

- only other changes made were changing IEdmVault21 to 20 and IEdmFile17 to 16

- When I built the project the other day (when it ref'd the Interop dlls instead of the tlbs), the Register for COM Interop was checked and the add-in worked on next launch of SW.  Cleaning the project didn't seem to unregister the add-in so I refreshed my memory with a little searching and removed it manually with regasm /codebase /tlb /u, so I believe that's cleaned up.  But when I build the project that ref's the tlbs with Register for COM Interop checked it must not be registering because the add-in does not show up in SW add-in manager.  If I run regasm manually it complains about registering an unsigned assembly and wants the assembly to have strong name, but the add-in does register and loads when SW starts.

Thank you.

**Comment by jsculley** [comment]
> OK. I downloaded sources again, put them in new folder. I assume the new MSI is compiled for 2022?

Yes.  I have not restructured the project yet to have multiple SW versions.

> * The refs to the tlbs were broken when project loaded in VS (I'm guessing due to installed version of SW/PDM being older?)

Correct.  The project is looking for 2022, but changing them to your version should correct it.

> * only other changes made were changing IEdmVault21 to 20 and IEdmFile17 to 16

OK.

> * When I built the project the other day (when it ref'd the Interop dlls instead of the tlbs), the Register for COM Interop was checked and the add-in worked on next launch of SW.  Cleaning the project didn't seem to unregister the add-in so I refreshed my memory with a little searching and removed it manually with regasm /codebase /tlb /u, so I believe that's cleaned up.  But when I build the project that ref's the tlbs with Register for COM Interop checked it must not be registering because the add-in does not show up in SW add-in manager.  If I run regasm manually it complains about registering an unsigned assembly and wants the assembly to have strong name, but the add-in does register and loads when SW starts.
> 

One problem I have had in the past is that if I don't run Visual Studio as an administrator, the build will fail with an error like this:
![image](https://user-images.githubusercontent.com/8567569/175574031-ac5caa65-8df5-4937-af7b-a4dfeb0bbb1a.png)

So, first things first, try running as admin.  It's not enough to 'be' ad admin on your machine, you have to right click on the VS icon and select **Run as Admininstrator**.  You will have an **ADMIN** button in the top right when you do this:
![image](https://user-images.githubusercontent.com/8567569/175575158-51b8ad78-0692-4cc0-9a5b-7568aab09f5e.png)
Second, if you aren't already, don't bother with the installer yet.  Get the add-in running directly from Visual Studio.

When this is all set up correctly, you should not need to use regasm at all.

Also, what version of Visual Studio are you using?  I'm using VS 2022 Pro. It shouldn't matter but when it works for me and not for you, wee need to figure out what is different and go from there.

**Comment by nemecben** [comment]
Running VS as admin, after it reminded me on Wednesday.

Yep, not worried about using the msi file or installer project.  I just let VS register the add-in with build option.

I'm still on VS Comm 2019, now that it's unsupported I need to get up to date.

**edit:** _installed VS 2022  and the add-in now registers on build and loads when SW starts up.  I'm not aware of any other change after the last build in VS 2019, so it must have been version of VS.  My bad for still being on VS 2019._

**Comment by jsculley** [comment]
I have 2019 Pro available here.  I'll clone the repo and try a build on that and see if anything is different.

**Comment by jsculley** [comment]
2019 Pro is acting as you describe.  This is most likely a COM registration issue.  Visual Studio 2022 is a 64-bit app so everything just works.  VS 2019 is 32 bit, so it is registering the add-in incorrectly.  I changed the platform target to x64 in the Build section of the project properties and after a rebuild, the add-in loaded properly in SW.

**Comment by nemecben** [comment]
> 2019 Pro is acting as you describe. This is most likely a COM registration issue. Visual Studio 2022 is a 64-bit app so everything just works. VS 2019 is 32 bit, so it is registering the add-in incorrectly. **I changed the platform target to x64 in the Build section of the project properties and after a rebuild, the add-in loaded properly in SW.**

Sorry for being dense, but let me double check, in VS 2019 it only registered after build when platform set to 64 bit.  But in VS 2022 platform target can be "Any CPU" ?  

I believe this issue is resolved.

I've been debugging on my dev machine, will open another issue to document.

Thanks!

**Comment by jsculley** [comment]
> 
> Sorry for being dense, but let me double check, in VS 2019 it only registered after build when platform set to 64 bit. But in VS 2022 platform target can be "Any CPU" ?

Correct.  Visual Studio 2022 is the first version where Visual Studio itself is a 64 bit application (devenv.exe).  So it seems to handle COM registration for 64 bit DLLs by default whereas older versions you had to explicitly tell it you wanted 64 bit registration via the Platform Target.
